### ISSUE TITLE
Dont Know What To Do

### ISSUE THREAD

**Issue by Genesis25043** [adanvdo/YT-RED-UI#152]
![Screenshot 2023-09-09 110727](https://github.com/adanvdo/YT-RED-UI/assets/144515842/e1839b04-bb1a-432c-9e9d-3d7332fd7162)

**Comment by adanvdo** [comment]
@Genesis25043 try the latest alpha build and let me know if you still have the issue.
[v1.0.4.2-alpha](https://github.com/adanvdo/YT-RED-UI/releases/tag/v1.0.4.2-alpha)

**Comment by adanvdo** [comment]
@Genesis25043 are you still having issues?

**Comment by adanvdo** [comment]
closing this since there was no response. please feel free to re-open if you are still having issues @Genesis25043
